language: java
before_install:
  - wget http://services.gradle.org/distributions/gradle-1.1-bin.zip
  - unzip gradle-1.6-bin.zip
  - export GRADLE_HOME=$PWD/gradle-1.6
  - export PATH=$GRADLE_HOME/bin:$PATH
script: gradle check --info
after_failure:
  - "cat ./build/test-results/*.xml"
jdk:
  - oraclejdk8  

